name: Reproduce cache problems

on: [push, pull_request, workflow_dispatch]

jobs:
  repro:
    name: Reproduce cache problem
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        add-to-path: [true, false]
    steps:
      - name: Cache some random bits
        uses: actions/cache@941bc71a2416b1d47ddeaaf31691cacefc2c9060
        with:
          key: sample-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}-${{ strategy.job-index }}-${{ github.action }}
          path: C:\cygwin\var\log

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@db475590d56881c6cef7b3f96f6f3dd9532ea1f4
        with:
          add-to-path: ${{ matrix.add-to-path }}
